//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_order { get; set; }
        public Nullable<int> Id_manager { get; set; }
        public int Id_client { get; set; }
        public int Id_category_advertising { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Temp_of_delivery { get; set; }
        public string Date_of_withdrawal_of_adertising_turnover { get; set; }
        public string Product_name { get; set; }
        public string Description_wish { get; set; }
    
        public virtual Category_advertising Category_advertising { get; set; }
        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
